DROP DATABASE IF EXISTS conduit;

CREATE DATABASE conduit;

GRANT ALL ON conduit.* TO 'a' @ 'localhost' IDENTIFIED BY
  'password' WITH GRANT OPTION;

FLUSH PRIVILEGES;

SHOW DATABASES;

USE conduit;

CREATE EXTENSION IF NOT EXISTS citext;

