DROP DATABASE IF EXISTS conduit;

DROP DATABASE IF EXISTS conduit;

CREATE DATABASE conduit;
CREATE USER a WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE conduit TO a;

\connect conduit
CREATE EXTENSION IF NOT EXISTS citext;

